import { AnimationParams, utils } from "animejs";

type AnimationsPerAssetParams = {
    [key: string]: {
        extraTarget?: string[];
        animationConfig: AnimationParams;
    };
};
export const animationPerAsset: AnimationsPerAssetParams = {
    "sunny": {
        animationConfig: {
            rotate: () => utils.random(0, 60),
            duration: 3000,
            ease: "linear",
            loop: 10,
            alternate: true,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "mostly_cloudy": {
        extraTarget: ["g > g:last-of-type"],
        animationConfig: {
            translateX: 5,
            translateY: 40,
            duration: 3000,
            // ease: "cubicBezier(0.5, 0, 0.5, 1)",
            ease: "linear",
            loop: 10,
            alternate: true,
            autoplay: true,
            onLoop: () => {},
            onUpdate: () => {},
            // onBegin: self => console.log(self),
        },
    },
    "cloudy": { 
        animationConfig: {
            translateX: 8,
            duration: 3000,
            ease: "cubicBezier(0.5, 0, 0.5, 1)",
            loop: 10,
            alternate: true,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "fog": {
        animationConfig: {
            opacity: [0.7, 1],
            duration: 3000,
            ease: "cubicBezier(0.5, 0, 0.5, 1)",
            loop: 10,
            alternate: true,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "mostly_cloudy_w_showers": {
        extraTarget: ["g:nth-child(2) > path[fill='#168aa5']:last-of-type", "g:nth-child(2) > path[fill='#26a3b9']", "g:nth-child(2) > g[fill='#168aa5']"], 
        animationConfig: {
            duration: 2000,
            translateY: {
                from: "15px",
                to: "100px",
            },
            ease: "linear",
            loop: 10,
            alternate: false,
            autoplay: true,
            loopDelay: 600,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "t-storms": {
        extraTarget: ["g > path[fill='#26a3b9']:nth-child(1)"],
        animationConfig: {
            opacity: [0, 1],
            duration: () => utils.random(0, 600),
            ease: "outElastic(1, .5)",
            loop: 10,
            loopDelay: 1000,
            alternate: false,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "rain": {
        extraTarget: ["g:nth-child(2) > path[fill='#bdd9e5']", "g:nth-child(2) > path[fill='#26a3b9']"],
        animationConfig: {
            translateY: "60px",
            duration: 1600,
            ease: "linear",
            rotate: [0,2],
            loop: 10,
            alternate: false,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "flurries": {
        extraTarget: ["g > path[fill='#168aa5']", "g > path[fill='#26a3b9']"],
        animationConfig: {
            duration: 7500,
            translateY: "280px",
            ease: "linear",
            loop: 10,
            alternate: false,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "snow": {
        extraTarget: ["g > g[fill='#bdd9e5'], g > path[fill='#d9ecf2']"],
        animationConfig: {
            duration: 8500,
            translateY: "280px",
            ease: "linear",
            loop: 10,
            alternate: false,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "90": {
        animationConfig: {
            rotateZ: 10,
            duration: 1600,
            ease: "cubicBezier(0.5, 0, 0.5, 1)",
            loop: true,
            alternate: true,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "315": {
        animationConfig: {
            rotateZ: 10,
            duration: 1600,
            ease: "cubicBezier(0.5, 0, 0.5, 1)",
            loop: true,
            alternate: true,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "45": {
        animationConfig: {
            rotateZ: 10,
            duration: 1600,
            ease: "cubicBezier(0.5, 0, 0.5, 1)",
            loop: true,
            alternate: true,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "135": {
        animationConfig: {
            rotateZ: 10,
            duration: 1600,
            ease: "cubicBezier(0.5, 0, 0.5, 1)",
            loop: true,
            alternate: true,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "225": {
        animationConfig: {
            rotateZ: 10,
            duration: 1600,
            ease: "cubicBezier(0.5, 0, 0.5, 1)",
            loop: true,
            alternate: true,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
    "270": {
        animationConfig: {
            rotateZ: 10,
            duration: 1600,
            ease: "cubicBezier(0.5, 0, 0.5, 1)",
            loop: true,
            alternate: true,
            autoplay: true,
            onBegin: () => {},
            onLoop: () => {},
            onUpdate: () => {},
        },
    },
};