name: Deploy FWM NextJs App

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24.11.0"

            - uses: pnpm/action-setup@v5
              name: Install pnpm
              with:
                  version: 10
                  cache: true

            - name: Install dependencies
              run: pnpm install

            - name: Run Tests
              run: pnpm test

            - name: Deploy to the server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
                  script: |
                      cd /home/fwm/scripts
                      ./deploy_fwm_next_js.sh
